version: '3.8'

services:
  api:
    build:
      context: ./api
    volumes:
      - ./api:/app
    ports:
      - "8001:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  site:
    build:
      context: ./site
    volumes:
      - ./site:/app
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

