version: '3.8'

services:
  postgres:
    build:
      context: ./postgres
    container_name: postgres_db
    restart: always
    env_file: ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "/usr/local/bin/healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
    volumes:
      - ./api:/app
    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8001:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  site:
    build:
      context: ./site
    volumes:
      - ./site:/app
    depends_on:
      - api
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
